CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  profile_pic VARCHAR(500) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(100) PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS notes (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  note TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Menunggu',
  link VARCHAR(500) DEFAULT '',
  wallet VARCHAR(255) DEFAULT '',
  date TIMESTAMP DEFAULT NOW(),
  amount DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS settings (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  theme VARCHAR(20) DEFAULT 'azure',
  dark_mode BOOLEAN DEFAULT FALSE,
  notifications BOOLEAN DEFAULT TRUE
);
